name: custom_text_form_field_initial_value
description: "A customizable Flutter TextFormField widget with validations and optional initial value support."
version: 0.1.0
author: "Amit Chandra <camit97chandra@gmail.com>"
homepage: https://github.com/rahul12332
repository: https://github.com/rahul12332/custom_text_form_field_initial_value

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/custom_form_image.png
